#
# The contents of this file are subject to the terms of the Common Development and
#  Distribution License (the License). You may not use this file except in compliance with the
#  License.
#
#  You can obtain a copy of the License at https://forgerock.org/license/CDDLv1.0.html. See the License for the
#  specific language governing permission and limitations under the License.
#
#  When distributing Covered Software, include this CDDL Header Notice in each file and include
#  the License file at legal/CDDLv1.0.txt. If applicable, add the following below the CDDL
#  Header, with the fields enclosed by brackets [] replaced by your own identifying
#  information: "Portions copyright [year] [name of copyright owner]".
#
#  Copyright 2018 ForgeRock AS.
#
#

spring:
  application:
    name: exercise-tpp
  hostname: localhost
  jackson:
    default-property-inclusion: NON_NULL
  sleuth:
    sampler:
      percentage: 1.0

logging:
  level:
    com:
      forgerock:
        openbanking:
          sample: DEBUG

server:
    port: 8080
    ssl:
        enabled: true
        key-alias: transport
        key-password: changeit
        key-store: classpath:keystore/keystore.p12
        key-store-password: changeit

tpp:
  obri:
    domain: ob.forgerock.financial
  root: https://${spring.hostname}:${server.port}/open-banking/v1.1
  redirect-uris:
    aisp: https://${spring.hostname}:${server.port}/web/exchange_code/aisp   #<-- replace this by the redirect uri you have setup in your SSA
    pisp: https://${spring.hostname}:${server.port}/web/exchange_code/pisp  #<-- replace this by the redirect uri you have setup in your SSA
  openbanking:
    version: v2.0
  jwkms: https://jwkms.${tpp.obri.domain}
  directory:
    endpoint: https://service.directory.${tpp.obri.domain}
    user:
      username: demo
      password: changeit
  aspsp:
    financial-id: 0015800001041REAAY
    as-discovery-endpoint: https://as.aspsp.${tpp.obri.domain}/oauth2/
    rs-discovery-endpoint: https://rs.aspsp.${tpp.obri.domain}/open-banking/discovery

preregisteredTpp: classpath:backup/preregisteredForgeTppSample.json
